- name: configure dm
  template:
    src: "templates/{{item.1.file}}.j2"
    dest: "{{item.1.path}}/{{item.1.file}}"
  when: item.0.name == mydm
  with_subelements:
    - "{{ dms }}"
    - config
- name: In case kdm is used
  lineinfile:
    path: /etc/xscreensaver/XScreenSaver.ad.header
    regexp: "\\*newLoginCommand:.*"
    line: "*newLoginCommand:       kdmctl reserve"
    state: present
  notify: 'update screensaver hacks'
- name: Copy ressources
  copy:
    src: "{{item.file}}"
    dest: "{{item.path}}"
  with_items:
    - "{{ressources}}"
