---
- name: Install and remove packages
  tasks:
    - package: name= "{{ item }}" state=present
      with_items: "{{ dms.{{my_dm}}.packages }}"
    - package: name= "{{ item.packages }}" state=absent
      with_dict: "{{ dms }}"

    - file: path=/etc/systemd/system/display-manager.service state=absent
    - systemd: name= "{{ dms.{{my_dm}}.service }}" enabled=yes
    - shell: 'systemctl set-default graphical'
