---
- name: Install dm
  package: name="{{ item.1 }}" state=present
  when: item.0.name == mydm
  with_subelements:
    - "{{ dms }}"
    - packages
- name: Remove all other packages
  package: name="{{ item.1 }}" state=absent
  when: item.0.name != mydm
  with_subelements:
    - "{{ dms }}"
    - packages
- name: Del. display-manager.service
  file: path=/etc/systemd/system/display-manager.service state=absent
- name: install new display manager
  systemd: name= "{{ mydm }}" enabled=yes
- name: Set graphical target
  shell: 'systemctl set-default graphical'
